### ISSUE TITLE
[raspi3B] test script doesn't work!

### ISSUE THREAD

**Issue by RedsAnDev** [SAndroidEOfficial/framework#37]
Hi guys, 
I test bash script in pi's home of Raspi-SAndroidE-Image.
But, everytime I try command
`./test start`
I get this kind of message
```
pi@raspberrypi:~ $ ./test start
Starting gpio-peripheral.js
gpio - new Gpio n: 1, real gpio: 1
direction is: in
gpio - new Gpio n: 2, real gpio: 2
direction is: in
gpio - new Gpio n: 3, real gpio: 3
direction is: in

fs.js:537
  return binding.write(fd, buffer, offset, length, position);
                 ^
Error: EBUSY, resource busy or locked
    at Object.fs.writeSync (fs.js:537:18)
    at Object.fs.writeFileSync (fs.js:984:21)
    at new Gpio (/home/pi/node_modules/onoff/onoff.js:89:8)
    at new GPIO (/home/pi/BT_peripheral/gpio.js:94:12)
    at Object.<anonymous> (/home/pi/BT_peripheral/gpio-peripheral.js:48:36)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
```

Where is my mistake?

**Comment by drkangel** [comment]
Try to run the command with sudo

**Comment by giowild** [comment]
News on this? Does it work now?

**Comment by RedsAnDev** [comment]
ASAP

**Comment by giowild** [comment]
Please open this again if the issue is still not solved.
